version: '3.1'
services:
  rabbitmq:
        image: 'rabbitmq:3.7-management-alpine'
        ports:
            - '5672:5672'
            - '15672:15672'
  redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
